#
# private/config/app.dist.yaml
#

# defined any application-specific components here
components:

    # responsible for loading services and routes
    - Kispiox\Component\DefaultComponent
    - Popfasd\Ninja\Component\PopfasdNinjaComponent


# the main run routine [class, method]
run: ['Kispiox\Component\DefaultComponent', 'run']

# email addresses to receive notification that a submission has been received
mailto: []

# where ninja lives in relation to the document root (e.g. /ninja)
uriPrefix: /

# the query string key that contains validation results (defaults to '__nv')
validationKey: __nv

# the path to the cache directory (default is 'private/cache')
cacheDir: private/cache

# what storage driver to store form settings with (defaults to FileCache)
cacheProvider: Popfasd\Ninja\Cache\FileCache
