#
# private/config/routes.dist.yaml
#
# Route definitions
#
routes:

    get_submit:
        path:   '/submit'
        method: 'GET'
        action: 'Popfasd\Ninja\Controller:getSubmitAction'

    post_submit:
        path:   '/submit'
        method: 'POST'
        action: 'Popfasd\Ninja\Controller:postSubmitAction'

    api_auth:
        path:   '/api'
        action: 'Kispiox\Authentication\AuthController:authAction'

    submissions_get:
        path:   '/api/forms/{formId}/submissions'
        method: 'GET'
        action: 'Popfasd\Ninja\ApiController:getSubmissionsAction'

    form_get:
        path:   '/api/forms/{formId}'
        method: 'GET'
        action: 'Popfasd\Ninja\ApiController:getFormAction'

    forms_get:
        path:   '/api/forms'
        method: 'GET'
        action: 'Popfasd\Ninja\ApiController:getFormsAction'

    error_404:
        path:   '/'
        action: 'Popfasd\Ninja\Controller:error404Action'
