#
# private/config/routes.dist.yaml
#
# Route definitions
#
routes:

    api_token_verify:
        path:   '/submit'
        method: 'POST'
        action: 'Popfasd\Ninja\Controllers\ApiTokenController:verifyAction'

    post_submit:
        path:   '/submit'
        method: 'POST'
        action: 'Popfasd\Ninja\Controllers\SubmissionController:postSubmitAction'

    error_405_submit:
        path:   '/submit'
        action: 'Popfasd\Ninja\Controllers\ErrorController:error405Action'
        defaults: { methods: [ 'POST' ] }

    api_auth:
        path:   '/api/auth'
        method: 'POST'
        action: 'Kispiox\Authentication\AuthController:authenticateAction'

    api_verify_auth:
        path:   '/api'
        action: 'Kispiox\Authentication\AuthController:verifyAction'

    api_generate_token:
        path:   '/api/token'
        method: 'POST'
        action: 'Popfasd\Ninja\Controllers\ApiController:generateTokenAction'

    api_list_submissions:
        path:   '/api/forms/{formId}/submissions'
        method: 'GET'
        action: 'Popfasd\Ninja\Controllers\ApiController:getSubmissionsAction'

    api_export_form:
        path:   '/api/forms/{formId}/export'
        method: 'GET'
        action: 'Popfasd\Ninja\Controllers\ApiController:getExportAction'

    api_get_form:
        path:   '/api/forms/{formId}'
        method: 'GET'
        action: 'Popfasd\Ninja\Controllers\ApiController:getFormAction'

    api_list_forms:
        path:   '/api/forms'
        method: 'GET'
        action: 'Popfasd\Ninja\Controllers\ApiController:getFormsAction'

    error_404:
        path:   '/'
        action: 'Popfasd\Ninja\Controllers\ErrorController:error404Action'
