# email addresses to receive notification that a submission has been received
mailto: []

# where ninja lives in relation to the document root (e.g. /ninja)
uriPrefix:

# the path to the cache directory (default is 'private/cache')
cacheDir: private/cache

# the query string key that contains validation results (defaults to '__nv')
validationKey: __nv
